name: CI for Static Site
on:
 push:
   branches:
     -main 
     pull_request:
     branches:
     -main 
     
  jobs:
  build:
  runs-on: ubuntu-latest 
  
  steps: 
  -name:Checkout repository
  uses: actions/checkout@v2
  -name: Validate HTML files 
  uses:chrisderv/validate-html@v1
  with:
  path:
